### ISSUE TITLE
Process leak

### ISSUE THREAD

**Issue by 0xJes** [red/VScode-extension#31] opened 2018-11-24 07:24 UTC
When closing vscode or reloading window after opening a .red file, it leaks a process that is running `completion.red`, this process eats my whole free ram in matter of seconds... 

The normal behavior, i suppose...
![imagen](https://user-images.githubusercontent.com/30764221/48965572-3e0d6c00-ef96-11e8-83bf-e469efb1dbbb.png)

But when i close or reload window, this happens, the process is stopped so my pc doesn't run out of memory:
![imagen](https://user-images.githubusercontent.com/30764221/48965540-cd664f80-ef95-11e8-99f2-b8492587bcef.png)

I'm on arch linux, using vscode 1.29.1 and Red 0.6.3 stable, it happens with only this extension enabled.

**Comment by bitbegin** [comment] 2018-12-03 04:11
As it works in ubuntu, what's your OS desktop?

**Comment by qtxie** [comment] 2018-12-03 06:19
@bitbegin It's ArchLinux.

**Comment by qtxie** [comment] 2018-12-03 06:45
@JesMJM I cannot reproduce it on Windows 7, using vscode 1.29.1 and Red 0.6.4. Can you try the latest Red version? Maybe it's a bug in 0.6.3.

**Comment by bitbegin** [comment] 2018-12-03 06:46
I know it's ArchLinux, I also have install it, but the ArchLinux default only have CLI interface, you need install desktop like grome/kde/lxde ...

**Comment by 0xJes** [comment] 2018-12-03 11:34
I'm using Red 0.6.4 now, the problem persist but it eats ram way slower, my DE is KDE

**Comment by quan-nh** [comment] 2018-12-19 14:12
I got the same issue on MacOS, using vscode 1.30.1 and Red 0.6.4

**Comment by bitbegin** [comment] 2019-03-16 09:48
should be fixed in 0.3.0

**Closed as completed** 2019-03-16 12:22 UTC
Labels: bug
